### ISSUE TITLE
Finish setup page

### ISSUE THREAD

**Issue by Hanziness** [Hanziness/AnotherPomodoro#120]
The setup page should be able to let first-time users deeply configure the app for their first use.

## Tasks

* [x] Language switcher
* [x] Light or dark mode
* [x] A few grand presets that control a lot of settings (like a "minimal" one that disables everything on the UI, a "full-fledged" one that enables every feature)
* [x] Permissions: play audio, send notifications
* [x] Let users know where they can customise the app
* [x] (Optional) provide a (sort-of) live preview of the configuration
