### ISSUE TITLE
Major refactoring

### ISSUE THREAD

**Issue by Hanziness** [Hanziness/AnotherPomodoro#124]
Approaching 1.0 and having most features recently implemented, it's time to go through the app's code and perform a major cleanup by removing unneeded dependencies, checking for bad practices and performing general code and bundle optimisation.

## Tasks

* [x] Remove `vue-lazy-hydration` as it is most useful for SSR rendered applications (and not so much for static sites)
* [x] Use `@nuxt/image` for image optimization
* [x] Remove CSS `@apply` where possible (it's mostly bad practice when one could use components, too)
* [x] Check component import strategies
* [x] Upgrade dependencies
* [x] Clean up README and update screenshot(s)
* [x] Fix setup dark background not reaching bottom of the page
* [x] Check if more component templates can be marked as `functional`
* [x] #132
* [x] Check for other opportunities to reorganize code to make it more efficient
