### ISSUE TITLE
Implement a friendly error page

### ISSUE THREAD

**Issue by Hanziness** [Hanziness/AnotherPomodoro#126]
The default error page isn't very helpful as it doesn't help the user understand what went wrong with the application. A new error page layout should be implemented that also allows the user to reset the settings and reload the page in case something broke.

## Tasks

* [x] Make the design friendlier and more readable
* [x] Try to provide more details about the error
* [x] Provide buttons that reset the settings or reload the app (or lead to the GitHub issues page)
