### ISSUE TITLE
Feature: current task / task list

### ISSUE THREAD

**Issue by Hanziness** [Hanziness/AnotherPomodoro#19]
It might help personalize the app (and motivate users) that a user can specify what they want to do in a work/break/long pause section. Visually, they would see a "You wanted to do this: ..." reminder near the bottom of the screen. This might also help users adjust their section lengths accordingly.

Functionality planned:

- [ ] Basic TODO tracker functionality
- [ ] Persist with settings
- [ ] Ability to add separate entries for work/pause(/long pause) sections
- [ ] Pause sections might not need checkboxes
- [ ] Can be turned off entirely from the settings (like the schedule)
- [ ] Highlight top _x_ tasks while working
- [ ] Add descriptions to entries
- [ ] Hook into starting the timer and prevent starting it without selecting tasks for the current section
