### ISSUE TITLE
Unify support button logic

### ISSUE THREAD

**Issue by Hanziness** [Hanziness/AnotherPomodoro#241]
The support button is currently only linked to the Buy Me a Coffee page and it is present in multiple places. The button should be refactored to be easier to maintain by having it use a single code base and to allow changing its functionality depending on certain conditions. On some platforms (e.g. in the Play Store) it might be against policies to directly link to a payments page. Additionally, it might be handy to allow users to directly support the app using Stripe.

### Tasks

- [ ] Unify support button code (it should be the same component in all places used: the home page, the welcome screen and the settings menu)
- [ ] Allow changing the button's functionality to show a pop-up that direct support is not available on the current platform
- [ ] Allow direct support using Stripe
