### ISSUE TITLE
User stats and reports

### ISSUE THREAD

**Issue by Hanziness** [Hanziness/AnotherPomodoro#245]
The app should be able to display an overview of how much time the user has spent in each section. This is now possible thanks to #229. I imagine the user stats as a coloured bar which shows their performance today/this week, where each segment is of the colour of the section the user was in - when the timer was not running, it should instead be gray. As per feedback, users should be able to generate reports and download them - the latter part is probably easier if the app generated a printer-friendly page that can then be printed to PDF.

## Tasks

- [ ] Keep track of app events (like starting/pausing/stopping the timer, changing sections etc.)
- [ ] Visualize events on a bar
- [ ] Generate a printable report page
