### ISSUE TITLE
Platform modules

### ISSUE THREAD

**Issue by Hanziness** [Hanziness/AnotherPomodoro#256]
The app will potentially run inside a Flutter app, too (#246), requiring a different approach to notification handling and such. The app should have a runtime configuration variable that allows it to compile for both the web (where it will be a PWA) and a web app embedded into a mobile app (where it doesn't need PWA functionality and the notifications are handled by the app framework).

## Tasks
- [x] Allow specifying the platform to compile for (`web` or `mobile`)
- [x] (`mobile`) Create the `mobile` platform module composable that forwards app events to the parent app
- [x] (`mobile`) Allow setting other parameters (like additional padding requested)
- [x] (`mobile`) Make the app self-contained -- ie. work without internet
- [x] (`web`) Only inject PWA scripts and manifest link on `web`
