### ISSUE TITLE
Rebrand AnotherPomodoro to FocusTide

### ISSUE THREAD

**Issue by Hanziness** [Hanziness/AnotherPomodoro#272]
To avoid collisions (potentially on the legal side, too) on the use of the Pomodoro word, AnotherPomodoro should be renamed. I have seen comments from other app developers and people who cautioned people not to use the word in their applications since the "owners" of the copyright are strict with who can use it (e.g. removal of app from Google Play). 

So, the new name should be **FocusTide** (hopefully the focus and tide words straight from the dictionary are not copyrighted), the domain https://focustide.app is already connected and leads to the app. This should not be a lot of additional work, the logo and functionality will not change, though I will likely switch up the font, too, while I'm at it (we'll see what works best). I will probably keep the [another-pomodoro.app](https://another-pomodoro.app) domain name for another year to allow a smoother transition for people.

This refactor should be done to prevent potential future clashes on the branding.

## Tasks

- [x] Rename displayed instances of "AnotherPomodoro" to FocusTide (links should be updated later)
- [x] Automatically update translations, too
- [x] Change display font to something new
